/******************************************************************************
 * File Name: main5_1.c
 *
 * Author: Ankit Rathi (ASU ID: 1207543476)
 *
 * Date: 05-DEC-2014
 *
 * Description: Use Linux signal handling mechanism, setjmp and longjmp 
 * to demonstrate an example imprecise computation programming pattern
 * in which executing computation will be terminated and the existing 
 * results are put out when we double click the right mouse button.
 *****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <linux/input.h>
#include <signal.h>
#include <string.h>
#include <setjmp.h>
#include <time.h>

#define MICE_DEVICE "/dev/input/event5"
#define RIGHT_CLICK_GAP 500

void *thread_mice_function(void *data);
void *thread_computation_function(void *data);
void signal_handler(int signo);

jmp_buf env_buffer;

/***********************************************************************
* main - Main Thread Function which creates two threads, one to get mice
* 	event inputs and other one to do the computation.
*
* Returns 0
* 
* Description:  Main Thread Function which creates two threads, one to 
* get mice event inputs and other one to do the computation.
***********************************************************************/
int main()
{
	pthread_t thread_mice, thread_computation;
	
	//Create pthreads
	pthread_create(&thread_mice, NULL, thread_mice_function, NULL);
	pthread_create(&thread_computation, NULL, thread_computation_function, NULL);

	//Wait for each of the thread to terminate.
	pthread_join(thread_mice, NULL);
	pthread_join(thread_computation, NULL);
	
	return 0;
}

/***********************************************************************
* thread_mice_function - Thread Function to get mice events. It is used
* 	to detect doucle right click events of mice.
* @data: Thread Parameters
*
* Returns NULL
* 
* Description: Thread Function to get mice events. It is used
* 	to detect doucle right click events of mice.
***************************************e********************************/
void *thread_mice_function(void *data)
{
	int fd_mice = 0;
	struct input_event ie;
	int firstClick = 0, secondClick = 0, clickCount = 0;
	struct timeval firstClick_timeStamp = {0}, secondClick_timeStamp = {0};
	long t_sec, t_usec, t_milli;
	
    if((fd_mice = open(MICE_DEVICE, O_RDONLY)) == -1)
    {
        printf("Mice Device opened Failed\n");
        exit(EXIT_FAILURE);
    }
    else
    {
		printf("Mice Device opened Successfully\n");
    }

    while(read(fd_mice, &ie, sizeof(struct input_event)))
    {
        if(ie.value == 1)
        {
			if(ie.code == 273)
			{
				if(clickCount == 0)
				{
					firstClick = 1;
					gettimeofday(&firstClick_timeStamp,NULL);
					secondClick = 0;
					clickCount++;
				}
				else
				{
					secondClick = 1;
					gettimeofday(&secondClick_timeStamp,NULL);
					clickCount++;
					
					t_sec  = secondClick_timeStamp.tv_sec  - firstClick_timeStamp.tv_sec;
					t_usec = secondClick_timeStamp.tv_usec - firstClick_timeStamp.tv_usec;
					t_milli = ((t_sec) * 1000 + t_milli/1000.0);
					if(t_milli < RIGHT_CLICK_GAP)
					{
						clickCount = 2;
						printf("Double Right Click Detected\n");
						raise(SIGUSR1);
					}
					else
					{
						firstClick_timeStamp = secondClick_timeStamp;
					}
				}
			}
		}
	}
}

/***********************************************************************
* thread_computation_function - Thread Function to get some computation.
* It waits for long jump to happen to to print the imprecisely
* 	computated value to the output screen.
* @data: Thread Parameters
*
* Returns NULL
* 
* Description: Thread Function to get mice events. It is used
* 	to detect doucle right click events of mice.
***************************************e********************************/
void *thread_computation_function(void *data)
{
	struct sigaction usr_action;
	sigset_t block_mask;
	int i=0;
	/* Establish the signal handler.  */
	memset(&usr_action, 0, sizeof(usr_action));
	usr_action.sa_handler = signal_handler;
	sigaction(SIGUSR1, &usr_action, NULL);
	if(setjmp(env_buffer) != 0)
	{
		printf("Existing Result = %d\n",i);
	}
	else
	{
		while(1)
		{
			i++;
			usleep(10000);
		}
	}
	pthread_exit(0);
}

/***********************************************************************
* signal_handler - Signal Handler Function. This function gets called
* 	as soon as event is generated by the mouse.
* @signo: Signal Number
*
* Returns NULL
* 
* Description: Signal Handler Function. This function gets called
* 	as soon as event is generated by the mouse.
***************************************e********************************/
void signal_handler(int signo)
{
	printf("Signal Handler called\n");
	longjmp(env_buffer, -1);
}
